name: Publish
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm install -g codecov
      - run: npm run test-cov
      - run: npm run report-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    name: Publish
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
